// Writes the shared network plumbing into every page of alexmerced.com.
//
// Reads network/network-head.html and network/network.json (both generated by
// build-network-shared.mjs; never edit them by hand) and rewrites the content
// between these markers in each page:
//
//   <!-- network:head:start --> ... <!-- network:head:end -->      GA4 tag + Person JSON-LD
//   <!-- network:cta:start --> ... <!-- network:cta:end -->        "Work with Alex" strip
//   <!-- network:footer:start --> ... <!-- network:footer:end -->  grouped network directory
//
// It also sets twitter:site from network.json. Pages that lack the head
// markers get them inserted before </head>; CTA and footer markers are placed
// by hand so each page decides where they sit. Runs as part of `npm run build`.
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';

const root = new URL('../', import.meta.url);
const head = readFileSync(new URL('network/network-head.html', root), 'utf8').trim();
const network = JSON.parse(readFileSync(new URL('network/network.json', root), 'utf8'));
const sites = JSON.parse(readFileSync(new URL('entity/sites.json', root), 'utf8')).sites;

const esc = value => String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;');
const local = url => url.replace(/^https:\/\/alexmerced\.com/, '') || '/';
const external = url => /^https?:\/\//.test(local(url));
const linkAttrs = url => (external(url) ? ' target="_blank" rel="noopener"' : '');

const { footer, cta, twitterSite } = network;
if (!footer?.groups?.length) throw new Error('network.json has no footer groups');

const footerHtml = `<nav class="footer__directory" aria-label="The Alex Merced Network">
        <div class="footer__run-title">The Alex Merced Network</div>
        <div class="footer__directory-grid">
${footer.groups.map(group => `          <div>
            <div class="footer__col-title">${esc(group.title)}</div>
            <ul class="footer__directory-list">
${group.links.map(link => `              <li><a href="${esc(local(link.url))}"${linkAttrs(link.url)}>${esc(link.title)}</a></li>`).join('\n')}
            </ul>
          </div>`).join('\n')}
        </div>
        <p class="footer__directory-all"><a href="${esc(local(footer.allSitesUrl))}">${esc(footer.allSitesLabel)} &rarr;</a></p>
      </nav>`;

const ctaHtml = cta
  ? `<section class="cta-strip" aria-labelledby="cta-strip-heading">
    <div class="container cta-strip__inner">
      <h2 class="cta-strip__heading" id="cta-strip-heading">${esc(cta.heading)}</h2>
      <div class="cta-strip__links">
${cta.links.map(link => `        <a class="btn btn--pro" href="${esc(local(link.url))}"${linkAttrs(link.url)} data-network-event="${esc(link.event)}">${esc(link.label)}</a>`).join('\n')}
      </div>
    </div>
  </section>`
  : '';

// The network directory page lists every live site with its one-line job.
const byDomain = new Map(sites.map(site => [site.domain, site]));
const domainOf = url => new URL(url).hostname.replace(/^www\./, '');
const directoryGroups = footer.groups.map(group => ({
  title: group.title,
  sites: group.links.filter(link => /^https?:/.test(link.url)).map(link => {
    const site = byDomain.get(domainOf(link.url));
    if (!site) throw new Error(`Footer link not in sites.json: ${link.url}`);
    return { title: link.title, url: link.url, role: site.role };
  })
}));
const rootSite = byDomain.get('alexmerced.com');
directoryGroups[0].sites.unshift({ title: rootSite.title, url: 'https://alexmerced.com/', role: rootSite.role });
const directoryHtml = `${directoryGroups.map(group => `<section class="network-group">
        <h2 class="network-group__title">${esc(group.title)}</h2>
        <ul class="network-list">
${group.sites.map(site => `          <li><a href="${esc(site.url)}"><strong>${esc(site.title)}</strong><span class="network-list__domain">${esc(domainOf(site.url))}</span><span class="network-list__role">${esc(site.role)}</span></a></li>`).join('\n')}
        </ul>
      </section>`).join('\n      ')}
      <script type="application/ld+json">${JSON.stringify({
        '@context': 'https://schema.org',
        '@type': 'ItemList',
        name: 'The Alex Merced Network',
        description: 'Every live site in the Alex Merced network, grouped by purpose, with the job each one does.',
        numberOfItems: directoryGroups.reduce((n, g) => n + g.sites.length, 0),
        itemListElement: directoryGroups.flatMap(g => g.sites).map((site, i) => ({
          '@type': 'ListItem',
          position: i + 1,
          item: { '@type': 'WebSite', name: site.title, url: site.url, description: site.role, creator: { '@id': 'https://alexmerced.com/#alexmerced' } }
        }))
      })}</script>`;

const replaceBlock = (html, name, content, file) => {
  const re = new RegExp(`(<!-- network:${name}:start -->)[\\s\\S]*?(<!-- network:${name}:end -->)`);
  if (!re.test(html)) return html;
  return html.replace(re, () => `<!-- network:${name}:start -->\n  ${content}\n  <!-- network:${name}:end -->`);
};

const pages = readdirSync(root).filter(name => name.endsWith('.html'));
for (const name of pages) {
  const path = new URL(name, root);
  let html = readFileSync(path, 'utf8');
  if (!html.includes('<!-- network:head:start -->')) {
    if (!html.includes('</head>')) throw new Error(`${name} has no </head>`);
    html = html.replace('</head>', '<!-- network:head:start -->\n<!-- network:head:end -->\n</head>');
  }
  html = replaceBlock(html, 'head', head, name);
  html = replaceBlock(html, 'cta', ctaHtml, name);
  html = replaceBlock(html, 'footer', footerHtml, name);
  html = replaceBlock(html, 'directory', directoryHtml, name);
  html = html.replace(/<meta (?:name|property)="twitter:site" content="[^"]*">/g, `<meta name="twitter:site" content="${esc(twitterSite)}">`);

  const personBlocks = (html.match(/"@type"\s*:\s*"Person"/g) || []).length;
  const gaLoads = (html.match(/googletagmanager\.com\/gtag\/js/g) || []).length;
  if (gaLoads !== 1) throw new Error(`${name}: expected one gtag loader, found ${gaLoads}`);
  if (personBlocks < 1) throw new Error(`${name}: missing network Person block`);
  writeFileSync(path, html);
}
console.log(`apply-network: ${pages.length} pages`);
